# Generated by Django 3.0.3 on 2020-04-17 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='gender',
            new_name='sex',
        ),
    ]
